<?php

$routes = [
    "/" => "HomeController@index",
    "/products" => "HomeController@products",
    "/product-item" => "HomeController@productItems",
    "/get-a-quote" => "HomeController@getQuote",
    "/about-us" => "HomeController@aboutUs",
    "/faqs" => "HomeController@faqs",
    "/submit-contact-form" => "HomeController@submitContactForm",
    "/submit-inquiry-form" => "HomeController@submitInquiryForm",
    "/request-product-search" => "HomeController@requestProductSearch",

    "/admin" => "AdminController@index",
    "/manage-products" => "AdminController@products",
    "/search-product" => "AdminController@searchProduct",
    "/add-product" => "AdminController@addProduct",
    "/create-add-product" => "AdminController@createProduct",
    "/delete-product"=> "AdminController@deleteProduct",
    "/edit-product/{id}"=> "AdminController@editProduct",
    "/save-edit-product"=> "AdminController@saveEditedProduct",
    "/image-carousel"=> "AdminController@imageCarousel",
    "/upload-image-carousel"=> "AdminController@uploadImageCarousel",
    "/request"=> "AdminController@request",
    "/request-details/{id}"=> "AdminController@requestDetails",
    "/listen-request-received"=> "AdminController@listenRequestReceived",
    "/search-quote-request"=> "AdminController@searchQuoteRequest",
    "/delete-quote-request"=> "AdminController@deleteQuote",
    "/manage-users" => "AdminController@users",
    "/create-new-user-account"=> "AdminController@createNewUserAccount",
    "/account" => "AdminController@userAccount",
    "/update-user-account"=> "AdminController@updateAccount",
    "/admin-login"=> "AdminController@login",
    "/account-login-request"=> "AdminController@loginRequest",
    "/admin-logout"=> "AdminController@logout"
];